### ISSUE TITLE
Hooks: Support just in time container building or pulling

### ISSUE THREAD

**Issue by thboop** [fhammerl/runner-hooks#55]
Currently, we we start a job, (or start a local composite action)

We pull down all of the containers to build, and containers to pull from dockerhub. You can see where that is done here: https://github.com/actions/runner/blob/users/tihuang/podman/src/Runner.Worker/ActionManager.cs#L104

Then, in the first step of a job, we build/pull down those containers. This makes a lot of sense for our current use case, it fails fast and quick, so it saves customers compute.

In a hook world, we are prioritizing the ease of creating hooks.

So, when we run the `run container step` hook, we will ask the hook to build or pull the image just in time, so we no longer need to do this at the start of a job.

We will need to add code to make sure we skip doing this if hooks are enabled, and make sure that doesn't break anything with how we invoke container actions. I think currently they check if a container id exists or they fail, we shouldn't do that.

**Comment by thboop** [comment]
Its not a bug but I can't remove the label :(

**Comment by ruvceskistefan** [comment]
Closed with #57
