### ISSUE TITLE
Support nodeJS in Alpine containers

### ISSUE THREAD

**Issue by fhammerl** [fhammerl/runner-hooks#58]
### How we run JS actions 

- We package .NET 6, node12 and node16 with the runner (literally in the tar.gz, there’s _dotnetsdk and _externals/node12|16)
- When we run a container job, we mount these folders on the container
- If you want to execute javascript (you are running a JS github Action), we mount these folders (let’s say node16) and run the JS action on the container, using the mounted node runtime

### The problem on alpine

- Run an alpine container on a linux host
- Mount the folder with the ‘node16’ to your container, and - it doesn’t work. Turns out alpine is such a slim linux distro that ‘normal’ node16 doesn’t work for it, it needs a special node16 runtime we call node16_alpine
- Therefore, when we’re running a JS github action on a container, we need to know if the container is alpine or not (we know it must be linux)
- We find out by running `StepHost.DetermineNodeRuntimeVersion` in `NodeScriptActionHandler`, which runs a docker command against the container
- With hooks, we can’t expect there to be docker at all so this no longer works

[So, instead, we give the user the option to save whether the container is alpine](https://github.com/thboop/hooks/blob/main/docs/adr.md#:~:text=8080%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22network%22%3A%20%22github_network_53269bd575974817b43f4733536b200c%22%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20%22-,alpine%3A%20true,-%2C%0A%7D), then we can make a decision based on that

[Here’s the method where we currently just throw new notimplemented](https://github.slack.com/archives/D033RP2S3PV/p1650963745421209)
https://github.com/fhammerl/runner-hooks/blob/07d72d44ff62dc1a93e95173b42097ff6ba63724/src/Runner.Worker/Handlers/StepHost.cs#L137

**Comment by ruvceskistefan** [comment]
Closed with #59
