### ISSUE TITLE
Continue even if responseFile doesn't exist

### ISSUE THREAD

**Issue by fhammerl** [fhammerl/runner-hooks#65]
https://github.com/actions/runner/pull/1853/files#r864642011

The user will miss out on some data normally available in the context, but the hooks can work without it.

**Comment by ruvceskistefan** [comment]
Closed by next commits:
https://github.com/fhammerl/runner-hooks/commit/3b4e6c21e0816485b4d831244818939a44f6829c
https://github.com/fhammerl/runner-hooks/commit/973777d385519d116c8d2a6897572f43f3c53711
https://github.com/fhammerl/runner-hooks/commit/93bcf651d7e525e2938d2dd73862a66e4ae0530f
