### ISSUE TITLE
We shouldn't send over entry point / entry point args for job or service containers

### ISSUE THREAD

**Issue by thboop** [fhammerl/runner-hooks#70]
The runner just currently hard codes these, they shouldn't persist to the hook implementation, if hooks want to hard code them, they can.

**Comment by fhammerl** [comment]
Isn't it useful to give some defaults like this?
```
      "entryPointArgs": ["-f", "/dev/null"],
      "entryPoint": "tail",
```

The hooks can just override it then.

**Comment by fhammerl** [comment]
As per previous discussion, let's remove these 'default' args to avoid confusion deliberate args set by the user. The hook author can then be responsible for deciding on default args for their images.
